print("what is the tallest building in town?")
input()
print("The library, because it has the most stories!")
print("Now the next joke!")
input()
print("Why was the math book sad?")
input()
print("Because it had too many problems!")
print("Now the next joke!")
input()
print("What is a witch's favorite subject?")
input()
print("spelling!")
print("Now the next joke!")
input()
print("What do you call the king of all school supplies?")
input()
print("The ruler!")