print("hi I will be your host today!")
name= input ("what is your name?")
print(f"hello {name} welcome to CT8")
day=input("hows your day going?")
print (f"oh same i having a {day} day too")
print ("I have a great joke! if you dont want to hear it to bad!")
input()
print("what do you call a sleeping dinosaur?")
input()
print("a dino-snore!!")
input()
print("Why don't scientists trust atoms?")
input()
print("Because they make up everything!")
input()
print("enough with the jokes")
animal=print("tell me your favorite {animal}")
